app/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.column(db.String(30))
    username = db.Column(db.String(255))
    image = db.Column(db.String,  default='default.jpg')
    email = db.Column(db.String(30))
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch', backref='author', lazy='dynamic')
    comments = db.relationship('Comment', backref='comment', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.id}, {self.name}, {self.username}, {self.image}, {self.email}, {self.pitches}, {self.comment}'


class Comment(db.Model, UserMixin):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    ratings = db.Column(db.Integer)
    like = db.Column(db.Integer)
    dislike = db.Column(db.Integer)
    content = db.Column(db.Text)
    time = db.Column(db.DateTime)
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def __repr__(self):
        return f'Comment {self.id}, {self.ratings}, {self.like}, {self.dislike}, {self.content}'


class Pitch(db.Model, UserMixin):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    content = db.Column(db.Text)
    category = db.Column(db.String)
    comments_id = db.relationship(
        'Comment', backref='comments', lazy='dynamic')
    time = db.Column(db.DateTime)

    def __repr__(self):
        return f'Pitch {self.id}, {self.category}, {self.title}, {self.author}, {self.content}, {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
# from wtforms.validators import Required, Email, EqualTo
from ..models import User
from wtforms import ValidationError
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField


class UpdateProfile(FlaskForm):
    username = TextAreaField('enter username')
    submit = SubmitField('Submit')


class PitchForm(FlaskForm):
    title = StringField('Pitch title')
    category = SelectField('Pitch Category', choices=[('product', 'product'),
                                                      ('service', 'service'),         ('promotion', 'promotion'),     ('interview', 'interview')])
    content = TextAreaField('pitch your pitch')

    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    content = TextAreaField('comment')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask import Blueprint
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


# bootstrap = Bootstrap()
db = SQLAlchemy()
bootstrap = Bootstrap()
# Initializing application
photos = UploadSet('photos', IMAGES)
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)
    # ...
    app.config.from_object(config_options[config_name])

    # Setting up configuration

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    configure_uploads(app, photos)

    # configure UploadSetconfigure_uploads(app, photos)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views
from . import views, forms

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from flask_login import login_required, current_user
from . import main
from ..models import User, Pitch, Comment
from .forms import *
from .. import db, photos
from datetime import datetime
# Views


@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''

    title = 'Home - Welcome to The best Movie Review Website Online'
    pitches = Pitch.query.all()

    return render_template('index.html', title=title, pitches=pitches)


@main.route('/user/<name>')
def profile(name):
    user = User.query.filter_by(username=name).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)


@main.route('/user/<name>/update', methods=['GET', 'POST'])
@login_required
def update_profile(name):
    user = User.query.filter_by(username=name).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.username = form.username.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', name=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<name>/update/pic', methods=['POST'])
@login_required
def update_pic(name):
    user = User.query.filter_by(username=name).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.image = path
        db.session.commit()
    return redirect(url_for('main.profile', name=name))


@main.route('/pitch/', methods=['GET', 'POST'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():

        content = form.content.data
        title = form.title.data
        category = form.category.data
        # Updated review instance
        new_pitch = Pitch(
            content=content, title=title, category=category)
        db.session.add(new_pitch)
        db.session.commit()
        # save review method
        # new_pitch.save_pitch()
        # return redirect(url_for('.pitch', id=pitch.id))

    return render_template('pitches.html', pitch_form=form)


@main.route('/pitch/comment/new/<int:id>', methods=['GET', 'POST'])
@login_required
def new_comment(id):
    '''
    view category that returns a form to create a new comment
    '''

    form = CommentForm()
    pitch = Pitch.query.filter_by(id=id).first()

    if form.validate_on_submit():
        title = form.title.data
        comment = form.comment.data

        # comment instance
        new_comment = Comment(
            pitch_id=pitch.id, post_comment=comment, title=title, user=current_user)

        # save comment
        new_comment.save_comment()

        return redirect(url_for('.pitches', id=pitch.id))

    title = f'{pitch.title} comment'
    return render_template('newcomment.html', title=title, comment_form=form, pitch=pitch, )


@main.route('/allpitches')
def pitch_list():

    pitches = Pitch.query.all()

    return render_template('pitches.html', pitches=pitches)


@main.route('/onepitch/<int:id>', methods=['GET', 'POST'])
def one_pitch(id):

    pitch = Pitch.query.get(id)
    form = CommentForm()
    pitch = Pitch.query.filter_by(id=id).first()

    if form.validate_on_submit():
        # comment instance
        new_comment = Comment(
            ratings=0,
            like=0,
            dislike=0,
            content=form.content.data,
            time=datetime.utcnow(),
            comments=pitch,
            comment=current_user)

        # save comment
        db.session.add(new_comment)
        db.session.commit()

    comments = pitch.comments_id

    return render_template('viewpitch.html', pitch=pitch, id=id, comment_form=form, comments=comments)

app/views.py
from flask import render_template
from app import app
from flask_login import login_required


# Views


@app.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''

    title = 'Home - Welcome to The best Movie Review Website Online'
    return render_template('index.html', title=title)


@app.route('/pitch', methods=['GET', 'POST'])
@login_required
def new_review(id):
    pass

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
{%include 'navbar.html'%}
{% endblock %}

app/templates/comments.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}

{{ wtf.quick_form(comment_form) }} {{simplemde.load}}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}{% block content %}
<!DOCTYPE html>
<html>

<head>
</head>

<body>
    <div class="jumbotron text-center" id="jumbo1">
        <button type="button" class="text-center btn btn-warning" id="button1"><a href="/pitch"> Add Pitch</a></button>
    </div>
    {% for pitch in pitches%}
    <div class="container">
        <div class="jumbotron">
            <div class="card-columns">
                <h4></h4>
                <div class="card">
                    <h4 class="card-title"><strong><a href="/onepitch/{{pitch.id}}"> {{pitch.title | capitalize}}</a></strong></h4>
                    <p class="card-text">category:{{pitch.category}}</p><br>
                    <p class="card-text">Time posted:{{pitch.time}}</p><br>
                    <div class="card-body">
                        <h4 class="text-center">Your pitch:</h4><br>
                        <p>{{pitch.content}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

{% endfor %}
{% endblock%}

app/templates/interview.html
{% extends 'base.html' %} {% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles %} {% endblock %}

<!-- Content block -->
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {{macro.displayPitchList(interview)}}
    </div>
</div>
{% endblock %}

app/templates/macros.html
{% macro displayPitchList(pitch_list) %} {% for pitch in pitch_list %}
<div class="col-xs-6 col-sm-6 col-md-6">
    <div class="card m-2">
        <div class="card-header">
            Category - {{pitch.category_id}}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{pitch.title}}</h5>
            <p class="card-text">{{pitch.pitch}}</p>
        </div>
    </div>
</div>
{% endfor %} {% endmacro %}

app/templates/navbar.html
<div id="nav">
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> pitchers table </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li>
                        <div class="dropdown dropright" data-toggle="">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                categories
                            </button>
                            <div class="dropdown-menu" id="dropdown">
                                <a class="dropdown-item" href="pickup.html">pickup lines </a><br>
                                <a class="dropdown-item" href="interview.html">interview pitch </a><br>
                                <a class="dropdown-item" href="product.html">product pitch </a><br>
                                <a class="dropdown-item" href="promotion.html">promotion pitch </a><br>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',name=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</div>

app/templates/pickup.html
{% extends 'base.html' %} {% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles %} {% endblock %}

<!-- Content block -->
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {{macro.displayPitchList(pickup)}}
    </div>
</div>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}

{{wtf.quick_form(pitch_form)}}
{% endblock%}

app/templates/pitches.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}

{{wtf.quick_form(pitch_form)}}
{% endblock%}

app/templates/product.html
{% extends 'base.html' %} {% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles %} {% endblock %}

<!-- Content block -->
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {{macro.displayPitchList(product)}}
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.image %}
            <img src="{{url_for('static',filename=user.image)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        </div>
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.email %}
            <p> {{user.email}}</p>
            {%else%}
            <p> {{user.email| capitalize}} has no user name </p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',name=user.username)}}">Edit profile</a>
            {% endif %}
        </div>
        <div class="col-md-4">
            <!-- {% if user.image %}

                <img src="{{url_for('static',filename=user.image)}}" alt="" class="img-thumbnail">

                {%else%}
                <p>No profile picture</p>

                {% endif %} -->

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/promotion.html
{% extends 'base.html' %} {% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles %} {% endblock %}

<!-- Content block -->
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {{macro.displayPitchList(promotion)}}
    </div>
</div>
{% endblock %}

app/templates/viewpitch.html
{% extends 'base.html' %}{% import "bootstrap/wtf.html" as wtf %}{% block content %}
<div class="container">
    <div class="jumbotron">
        <div class="card-columns">
            <h4></h4>
            <div class="card">
                <h4 class="card-title"><strong><a href="/onepitch/{{pitch.id}}"> {{pitch.title | capitalize}}</a></strong></h4>
                <p class="card-text">category:{{pitch.category}}</p><br>
                <p class="card-text">Time posted:{{pitch.time}}</p><br>
                <div class="card-body">
                    <h4 class="text-center">Your pitch:</h4><br>
                    <p>{{pitch.content}}</p>
                    {{ wtf.quick_form(comment_form) }}
                    {%for comment in comments%}
                    <div class="jumbotron">

                        <p>{{comment.content}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>
{%endfor%}
{% endblock%}